# docker-compose.yml

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: projectpaldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_NAME: projectpaldb
      DB_USER: admin
      DB_PASSWORD: 12345
      DB_HOST: db
