# Generated by Django 4.2.17 on 2025-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geocode',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
