# Generated by Django 4.2.17 on 2025-02-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_point', '0002_address_geocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geocode',
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
