# Generated by Django 4.2.17 on 2024-12-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': 'Engineer'},
        ),
        migrations.RenameField(
            model_name='engineer',
            old_name='currentProj',
            new_name='current_project',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='dob',
            field=models.DateField(default='2001-10-20'),
        ),
    ]
