# Generated by Django 4.2.17 on 2025-02-28 03:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='elevator_pitch',
            field=models.FileField(blank=True, upload_to=accounts.models.video_upload_path),
        ),
    ]
