# Generated by Django 4.2.17 on 2025-01-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='current_project',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
