# Generated by Django 4.2.17 on 2025-02-28 03:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_engineer_elevator_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='elevator_pitch',
            field=models.FileField(null=True, upload_to=accounts.models.video_upload_path),
        ),
    ]
