# Generated by Django 4.2.17 on 2024-12-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_engineer_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='current_project',
            new_name='currentProj',
        ),
    ]
