# Generated by Django 4.2.17 on 2025-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address_state_address_street_address_zip_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='address',
        ),
        migrations.AddField(
            model_name='engineer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
