# Generated by Django 4.2.17 on 2024-12-31 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_current_project_engineer_currentproj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='currentProj',
            new_name='current_project',
        ),
    ]
