# Generated by Django 4.2.17 on 2025-02-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_address_state_remove_address_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='address',
        ),
        migrations.AddField(
            model_name='engineer',
            name='address',
            field=models.ManyToManyField(blank=True, to='accounts.address'),
        ),
    ]
