# Generated by Django 4.2.17 on 2025-02-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0009_remove_engineer_city_remove_engineer_country_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='address',
        ),
        migrations.AddField(
            model_name='engineer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
