# Generated by Django 4.2.17 on 2025-02-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0010_remove_engineer_address_engineer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='country',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
            ],
        ),
        migrations.AddField(
            model_name='engineer',
            name='address',
            field=models.ManyToManyField(blank=True, to='accounts.address'),
        ),
    ]
