# Generated by Django 4.2.17 on 2025-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_engineer_city_remove_engineer_country_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='address',
        ),
        migrations.AddField(
            model_name='engineer',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
