# Generated by Django 4.2.17 on 2025-02-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_engineer_address_engineer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='address',
        ),
    ]
