# Generated by Django 4.2.17 on 2025-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room_token',
            field=models.CharField(default='BZA51i6IVTEcYMRS8tA8', max_length=255),
        ),
    ]
