# Generated by Django 4.2.17 on 2025-02-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0002_meeting_room_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='room',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_token',
            field=models.CharField(default='ZSNhewdnlmeWtWMAGe95', max_length=255),
        ),
    ]
