# Generated by Django 4.2.17 on 2025-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0004_alter_meeting_room_token_alter_meeting_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingrequest',
            old_name='topic',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room_token',
            field=models.CharField(default='Yt9NOepYaCgD7OZy1Hrt', max_length=255),
        ),
    ]
