# Generated by Django 4.2.17 on 2024-12-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
