# Generated by Django 4.2.17 on 2024-12-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_engineer_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name_plural': 'Engineers'},
        ),
    ]
