# Generated by Django 4.2.17 on 2025-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='GAbIYYLnMrik8C4cjh5i', max_length=255),
        ),
    ]
