# Generated by Django 4.2.17 on 2025-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='bGW1oLR3xVAPlDZO0W6p', max_length=255),
        ),
    ]
