# Generated by Django 4.2.17 on 2025-02-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0002_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='GPFx8xAmabyh37biC0dJ', max_length=255),
        ),
    ]
