# Generated by Django 4.2.17 on 2025-01-20 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0002_alter_room_room_id_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('3a88fb86-6985-41cc-8f87-56256110dfe1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='VXD7lkUTYqaFmvRoMFd5', max_length=255),
        ),
    ]
