# Generated by Django 4.2.17 on 2025-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0002_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='4Qx0FI45nD1QAF0Twusy', max_length=255),
        ),
    ]
