# Generated by Django 4.2.17 on 2025-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0003_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='OSO2w5PXDn4HrzaOwP7f', max_length=255),
        ),
    ]
