# Generated by Django 4.2.17 on 2025-02-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0003_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='iOdX9C5vwh48cxen8EAI', max_length=255),
        ),
    ]
