# Generated by Django 4.2.17 on 2025-01-20 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0003_alter_room_room_id_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.UUID('e02212a0-04ad-4072-afdf-80080ca3e680'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='xdHi0yrwYLiOF7cXFpey', max_length=255),
        ),
    ]
