# Generated by Django 4.2.17 on 2025-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0004_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='iLfLUXJAWpyXHVolaOVL', max_length=255),
        ),
    ]
