# Generated by Django 4.2.17 on 2025-01-20 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0004_alter_room_room_id_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='EId8Z4qKOItX1C6JiS3I', max_length=255),
        ),
    ]
