# Generated by Django 4.2.17 on 2025-02-17 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_chat', '0005_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='7pBB8lVYApPt6YrebOuC', max_length=255),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Reply channel for connection that is present', max_length=255)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_chat.room')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'channel_name')},
            },
        ),
    ]
