# Generated by Django 4.2.17 on 2025-01-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0006_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='072NzPGVjfRBtXS2QG55', max_length=255),
        ),
    ]
