# Generated by Django 4.2.17 on 2025-02-17 20:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0006_alter_room_token_presence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presence',
            name='room_identification',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='inMSp3oPWifrtxY4PSTp', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('room', 'room_identification')},
        ),
        migrations.RemoveField(
            model_name='presence',
            name='channel_name',
        ),
    ]
