# Generated by Django 4.2.17 on 2025-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0007_alter_presence_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='room_identification',
            new_name='channel_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='0HeikWUWQ5TCJOQ0tyfY', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('room', 'channel_name')},
        ),
    ]
