# Generated by Django 4.2.17 on 2025-02-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0007_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='cAPe89IxNkKqaxmQi2qn', max_length=255),
        ),
    ]
