# Generated by Django 4.2.17 on 2025-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0008_rename_room_identification_presence_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='channel_name',
            field=models.CharField(help_text='Reply channel for connection that is present', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='qFm8mxFxmfI3kSKGZkID', max_length=255),
        ),
    ]
