# Generated by Django 4.2.17 on 2025-02-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0009_alter_presence_channel_name_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='emip2q6jGEL6rvoVWWPr', max_length=255),
        ),
    ]
