# Generated by Django 4.2.17 on 2025-02-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0009_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='fnswEL0gWIQMpy0DbnFn', max_length=255),
        ),
    ]
