# Generated by Django 4.2.17 on 2025-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0011_alter_room_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='channel_name',
            field=models.CharField(default='default added to add channel name to room model', help_text='Group channel name for this room', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='BCtX1GnJs88zAg5JYK36', max_length=255),
        ),
    ]
