# Generated by Django 4.2.17 on 2025-02-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0012_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='s7A5uEyisahztdUHKPfr', max_length=255),
        ),
    ]
