# Generated by Django 4.2.17 on 2025-02-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0012_room_channel_name_alter_room_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(help_text='Group channel name for this room', max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='channel_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='51YYAraeedOZRr4zy1Go', max_length=255),
        ),
    ]
