# Generated by Django 4.2.17 on 2025-02-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0013_videoroom_remove_room_channel_name_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_chat.videoroom'),
        ),
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='LW76eHLFRmNk712pdjDG', max_length=255),
        ),
    ]
