# Generated by Django 4.2.17 on 2025-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0014_alter_presence_room_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='03XDSXQ3fSdbmfkXVpEU', max_length=255),
        ),
    ]
