# Generated by Django 4.2.17 on 2025-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_chat', '0015_alter_room_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(default='xorIAh4Ist4i9BWeius6', max_length=255),
        ),
    ]
